config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'search', controller: :welcome, action: :search, format: false
  resources :tags, format: false
  resources :activities, format: false
  resources :attractions, format: false
end

app/models/activity.rb
class Activity < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :city
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :attractions

  validates :title, presence: true
  validates :description, presence: true

  after_touch() { __elasticsearch__.index_document }

  settings index: { number_of_shards: 1, number_of_replicas: 0, include_in_parent: true } do
    mappings do
      indexes :title, analyzer: 'russian'
      indexes :description, analyzer: 'russian'
      indexes :city, type: 'nested' do
        indexes :name, analyzer: 'russian'
      end

      indexes :tags, type: 'nested' do
        indexes :name, analyzer: 'russian'
      end

      indexes :attractions, type: 'nested' do
        indexes :name, analyzer: 'russian'
        indexes :description, analyzer: 'russian'
      end
    end
  end

  def as_indexed_json(options={})
    self.as_json(
      only: [ :title, :description ],
      include: {
        city: { only: :name },
        tags: { only: :name },
        attractions: { only: [:name, :description] }
      }
    )
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attraction.rb
class Attraction < ApplicationRecord
  has_and_belongs_to_many :activities
  belongs_to :city

  validates :title, presence: true
  validates :description, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :activities
  belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :activities

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def show
    @item = Activity.find(params[:id])
  end

  def index
    @items = Activity.page(params[:page])
  end

  def new
    @item = Activity.new
  end

  def create
    @item = Activity.new(attributes)

    return render action: :new unless @item.valid?

    @item.save!
    redirect_to @item
  end

  def edit
    @item = Activity.find(params[:id])
  end

  def update
    @item = Activity.find(params[:id])

    @item.assign_attributes(attributes)
    return render action: :edit unless @item.valid?

    @item.save!
    redirect_to @item
  end

  private
  def attributes
    params.require(:activity).permit(:title, :description, :city_id, :tag_ids => [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  def show
    @item = Attraction.find(params[:id])
  end

  def index
    @items = Attraction.page(params[:page])
  end

  def new
    @item = Attraction.new
  end

  def create
    @item = Attraction.new(attributes)

    return render action: :new unless @item.valid?

    @item.save!
    redirect_to @item
  end

  def edit
    @item = Attraction.find(params[:id])
  end

  def update
    @item = Attraction.find(params[:id])

    @item.assign_attributes(attributes)
    return render action: :edit unless @item.valid?

    @item.save!
    redirect_to @item
  end

  private
  def attributes
    params.require(:attraction).permit(:title, :description, :city_id, :activity_ids => [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @item = Tag.find(params[:id])
  end

  def index
    @items = Tag.all
  end

  def new
    @item = Tag.new
  end

  def create
    @item = Tag.new(attributes)

    return render action: :new unless @item.valid?

    @item.save!
    redirect_to @item
  end

  def edit
    @item = Tag.find(params[:id])
  end

  def update
    @item = Tag.find(params[:id])

    @item.assign_attributes(attributes)
    return render action: :edit unless @item.valid?

    @item.save!
    redirect_to @item
  end

  private
  def attributes
    params.require(:tag).permit(:name, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def search
    search_query = params[:q].downcase
    return redirect_to action: :index if search_query.empty?

    @items = Activity
                .search(
                  query: {
                    multi_match: {
                      query: search_query,
                      fields: %W(title description tags.name categories.name categories.description)
                    }
                  }
                )
                .page(params[:page])
                .records
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sitename
    "SputnikTask"
  end

  def preview_text(text, length = 200)
    "#{text[0...length]}..."
  end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/edit.html.haml
%h2.page-header= @item.title

.row
  .col-md-8.col-md-offset-2
    = simple_form_for @item, class: Activity do |f|
      = f.input :title
      = f.association :city
      = f.association :tags, as: :check_boxes
      = f.input :description, as: :text

      = f.button :submit, "OK"

app/views/activities/index.html.haml
%h2.page-header Экскурсии

- @items.each do |activity|
  = render 'shared/activity_list_item', activity: activity

= paginate @items

app/views/activities/new.html.haml
%h2.page-header Новая экскурсия

.row
  .col-md-8.col-md-offset-2
    = simple_form_for @item, class: Activity do |f|
      = f.input :title
      = f.association :city
      = f.association :tags, as: :check_boxes
      = f.input :description, as: :text

      = f.button :submit, "OK"

app/views/activities/show.html.haml
%h2.page-header
  = @item.title
  %small.text-success= @item.city.name
  %a.btn.btn-default.btn-xs{href: edit_activity_path(@item)}
    %i.glyphicon.glyphicon-pencil

%p= @item.description.html_safe

- @item.tags.each do |tag|
  %a.label.label-default{href: tag_path(tag)}= tag.name

%h3 Достопримечательности
- @item.attractions.each do |attraction|
  = render 'shared/attraction_list_item', attraction: attraction

app/views/attractions/edit.html.haml
%h2.page-header= @item.title

.row
  .col-md-8.col-md-offset-2
    = simple_form_for @item, class: Attraction do |f|
      = f.input :title
      = f.association :city
      = f.association :activities, as: :check_boxes
      = f.input :description, as: :text

      = f.button :submit, "OK"

app/views/attractions/index.html.haml
%h2.page-header Достопримечательности

- @items.each do |attraction|
  = render 'shared/attraction_list_item', attraction: attraction

= paginate @items

app/views/attractions/new.html.haml
%h2.page-header Новая достопримечательность

.row
  .col-md-8.col-md-offset-2
    = simple_form_for @item, class: Attraction do |f|
      = f.input :title
      = f.association :city
      = f.association :activities, as: :check_boxes
      = f.input :description, as: :text

      = f.button :submit, "OK"

app/views/attractions/show.html.haml
%h2.page-header
  = @item.title
  %small.text-success= @item.city.name
  %a.btn.btn-default.btn-xs{href: edit_attraction_path(@item)}
    %i.glyphicon.glyphicon-pencil

%p= @item.description.html_safe

%h3 Экскурсии
- @item.activities.each do |activity|
  = render 'shared/activity_list_item', activity: activity

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title= sitename
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => root_path}= sitename
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Экскурсии
                %span.caret
              %ul.dropdown-menu
                %li= link_to "Все", activities_path
                %li= link_to "Новая", new_activity_path

            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Достопримечательности
                %span.caret
              %ul.dropdown-menu
                %li= link_to "Все", attractions_path
                %li= link_to "Новая", new_attraction_path

            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Тэги
                %span.caret
              %ul.dropdown-menu
                %li= link_to "Все", tags_path
                %li= link_to "Новый", new_tag_path
                
    .container
      = yield

app/views/shared/_activity_list_item.html.haml
.row
  .col-md-12
    .thumbnail
      .caption
        %h3=link_to activity.title, activity_path(activity)
        %h5.text-muted= activity.city.name

        %p= preview_text(activity.description)
        %p
          %a.btn.btn-primary.btn-sm{:href => activity_path(activity), :role => "button"} Подробнее

app/views/shared/_attraction_list_item.html.haml
.row
  .col-md-12
    .thumbnail
      .caption
        %h3=link_to attraction.title, attraction_path(attraction)
        %p= attraction.description

app/views/shared/_search_form.html.haml
%form{action: search_path, method: :get}
  .input-group
    %input.form-control{placeholder: "Найдется всё и вся", type: "text", name: :q, value: params[:q]}
    %span.input-group-btn
      %button.btn.btn-default{:type => "submit"} Искать

app/views/tags/edit.html.haml
%h2.page-header= @item.name

.row
  .col-md-8.col-md-offset-2
    = simple_form_for @item, class: Tag do |f|
      = f.input :name
      = f.input :description, as: :text

      = f.button :submit, "OK"

app/views/tags/index.html.haml
%h2.page-header Тэги

%ul.list-group
  - @items.each do |tag|
    %li.list-group-item
      = link_to tag.name, tag_path(tag)
      %a.btn.btn-link.btn-xs{href: edit_tag_path(tag)}
        %i.glyphicon.glyphicon-pencil

app/views/tags/new.html.haml
%h2.page-header Новый тэг

.row
  .col-md-8.col-md-offset-2
    = simple_form_for @item, class: Tag do |f|
      = f.input :name
      = f.input :description, as: :text

      = f.button :submit, "OK"

app/views/tags/show.html.haml
%h2.page-header= @item.name

- @item.activities.each do |activity|
  = render 'shared/activity_list_item', activity: activity

app/views/welcome/index.html.haml
.row
  .col-md-8.col-md-offset-2{style: 'margin-top: 20%'}
    %h2 Поиск
    = render 'shared/search_form'

app/views/welcome/search.html.haml
%h2
  .page-header
    Результаты поиска
    %small= "(#{@items.count})"

.row
  .col-md-12{style: 'margin-bottom: 20px'}
    = render 'shared/search_form'

- if @items.empty?
  %h3 Результатов нет

- @items.each do |activity|
  = render 'shared/activity_list_item', activity: activity

= paginate @items